# Generated by Django 5.2.6 on 2026-04-08 20:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_reference', models.CharField(max_length=32, unique=True)),
                ('event_type', models.CharField(choices=[('movie', 'Movie'), ('sport', 'Sport')], max_length=24)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('simulated', 'Simulated')], default='simulated', max_length=24)),
                ('event_title', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('venue_name', models.CharField(max_length=255)),
                ('starts_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('filter_snapshot', models.JSONField(blank=True, default=dict)),
                ('event_snapshot', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('movie_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='events.movieevent')),
                ('sport_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='events.sportevent')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='chats.chatthread')),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-confirmed_at'],
                'indexes': [models.Index(fields=['event_type', '-confirmed_at'], name='booking_type_recent_idx'), models.Index(fields=['thread'], name='booking_thread_idx')],
            },
        ),
    ]
