# Generated by Codex on 2026-04-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="customer_contact_number",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="booking",
            name="customer_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="booking",
            name="customer_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
