# Generated by Django 6.0.4 on 2026-04-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_code', models.CharField(max_length=64, unique=True)),
                ('provider', models.CharField(db_index=True, max_length=64)),
                ('provider_offer_id', models.CharField(blank=True, max_length=128)),
                ('source_label', models.CharField(blank=True, max_length=64)),
                ('origin_iata', models.CharField(db_index=True, max_length=8)),
                ('origin_airport_name', models.CharField(blank=True, max_length=255)),
                ('origin_city', models.CharField(db_index=True, max_length=120)),
                ('origin_state', models.CharField(blank=True, max_length=120)),
                ('destination_iata', models.CharField(db_index=True, max_length=8)),
                ('destination_airport_name', models.CharField(blank=True, max_length=255)),
                ('destination_city', models.CharField(db_index=True, max_length=120)),
                ('destination_state', models.CharField(blank=True, max_length=120)),
                ('departure_date', models.DateField(db_index=True)),
                ('departure_at', models.DateTimeField(db_index=True)),
                ('arrival_at', models.DateTimeField(db_index=True)),
                ('airline_code', models.CharField(blank=True, max_length=16)),
                ('airline_name', models.CharField(db_index=True, max_length=255)),
                ('flight_number', models.CharField(db_index=True, max_length=32)),
                ('cabin_class', models.CharField(blank=True, max_length=64)),
                ('stops', models.PositiveSmallIntegerField(default=0)),
                ('refundable', models.BooleanField(default=False)),
                ('baggage_summary', models.CharField(blank=True, max_length=255)),
                ('fare_brand', models.CharField(blank=True, max_length=120)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('offer_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'flight_offers',
                'ordering': ['departure_date', 'departure_at', 'origin_city', 'destination_city'],
                'indexes': [models.Index(fields=['origin_city', 'destination_city', 'departure_date'], name='flight_route_date_idx'), models.Index(fields=['origin_iata', 'destination_iata', 'departure_date'], name='flight_iata_date_idx'), models.Index(fields=['airline_name'], name='flight_airline_idx'), models.Index(fields=['departure_at'], name='flight_departure_at_idx'), models.Index(fields=['is_published'], name='flight_published_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('provider_offer_id', ''), _negated=True), fields=('provider', 'provider_offer_id'), name='flight_provider_offer_unique')],
            },
        ),
    ]
