# Generated by Django 6.0.4 on 2026-04-14 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_chatthread_mode'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('simulated', 'Simulated')], default='simulated', max_length=24)),
                ('listing_code', models.CharField(db_index=True, max_length=64)),
                ('route', models.CharField(max_length=255)),
                ('origin_city', models.CharField(max_length=120)),
                ('origin_iata', models.CharField(max_length=8)),
                ('destination_city', models.CharField(max_length=120)),
                ('destination_iata', models.CharField(max_length=8)),
                ('departure_at', models.DateTimeField()),
                ('arrival_at', models.DateTimeField()),
                ('departure_date', models.DateField()),
                ('airline_name', models.CharField(max_length=255)),
                ('flight_number', models.CharField(max_length=32)),
                ('cabin_class', models.CharField(blank=True, max_length=64)),
                ('stops', models.PositiveSmallIntegerField(default=0)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('passenger_name', models.CharField(blank=True, max_length=255)),
                ('passenger_email', models.EmailField(blank=True, max_length=254)),
                ('passenger_contact_number', models.CharField(blank=True, max_length=32)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('filter_snapshot', models.JSONField(blank=True, default=dict)),
                ('offer_snapshot', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='flights.flightoffer')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_bookings', to='chats.chatthread')),
            ],
            options={
                'db_table': 'flight_bookings',
                'ordering': ['-confirmed_at'],
                'indexes': [models.Index(fields=['thread'], name='flight_booking_thread_idx'), models.Index(fields=['listing_code', '-confirmed_at'], name='flight_booking_listing_idx')],
            },
        ),
    ]
