# Generated by Django 5.2.6 on 2026-04-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_code', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('event_date', models.DateField(db_index=True)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.CharField(db_index=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('venue_name', models.CharField(db_index=True, max_length=255)),
                ('venue_area', models.CharField(blank=True, max_length=255)),
                ('venue_address', models.TextField(blank=True)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('min_price', models.PositiveIntegerField(default=0)),
                ('max_price', models.PositiveIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source_label', models.CharField(blank=True, max_length=64)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('release_date', models.DateField(blank=True, db_index=True, null=True)),
                ('runtime_minutes', models.PositiveIntegerField(default=120)),
                ('certification', models.CharField(blank=True, max_length=32)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('cast', models.JSONField(blank=True, default=list)),
                ('directors', models.JSONField(blank=True, default=list)),
                ('formats', models.JSONField(blank=True, default=list)),
                ('franchise', models.CharField(blank=True, max_length=120)),
                ('synopsis', models.TextField(blank=True)),
                ('viewer_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('content_origin', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'db_table': 'movie_events',
                'ordering': ['event_date', 'start_at', 'title'],
                'abstract': False,
                'indexes': [models.Index(fields=['city', 'event_date'], name='movieevent_city_date_idx'), models.Index(fields=['venue_name', 'event_date'], name='movieevent_venue_date_idx'), models.Index(fields=['start_at'], name='movieevent_start_at_idx'), models.Index(fields=['title'], name='movie_title_idx'), models.Index(fields=['release_date'], name='movie_release_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='SportEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_code', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('event_date', models.DateField(db_index=True)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.CharField(db_index=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('venue_name', models.CharField(db_index=True, max_length=255)),
                ('venue_area', models.CharField(blank=True, max_length=255)),
                ('venue_address', models.TextField(blank=True)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('min_price', models.PositiveIntegerField(default=0)),
                ('max_price', models.PositiveIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source_label', models.CharField(blank=True, max_length=64)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sport_type', models.CharField(db_index=True, max_length=64)),
                ('tournament_name', models.CharField(db_index=True, max_length=255)),
                ('season_label', models.CharField(blank=True, max_length=64)),
                ('competition_stage', models.CharField(blank=True, max_length=64)),
                ('format_label', models.CharField(blank=True, max_length=64)),
                ('home_team', models.CharField(db_index=True, max_length=120)),
                ('away_team', models.CharField(db_index=True, max_length=120)),
                ('participant_names', models.JSONField(blank=True, default=list)),
                ('featured_athletes', models.JSONField(blank=True, default=list)),
                ('organizer', models.CharField(blank=True, max_length=255)),
                ('gate_open_at', models.DateTimeField(blank=True, null=True)),
                ('match_number', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sport_events',
                'ordering': ['event_date', 'start_at', 'sport_type', 'tournament_name'],
                'abstract': False,
                'indexes': [models.Index(fields=['city', 'event_date'], name='sportevent_city_date_idx'), models.Index(fields=['venue_name', 'event_date'], name='sportevent_venue_date_idx'), models.Index(fields=['start_at'], name='sportevent_start_at_idx'), models.Index(fields=['sport_type', 'event_date'], name='sport_type_date_idx'), models.Index(fields=['tournament_name'], name='sport_tournament_idx'), models.Index(fields=['home_team'], name='sport_home_team_idx'), models.Index(fields=['away_team'], name='sport_away_team_idx')],
            },
        ),
    ]
