# Generated by Django 5.2.6 on 2026-04-08 20:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('booked', 'Booked'), ('archived', 'Archived')], default='active', max_length=24)),
                ('last_message_preview', models.CharField(blank=True, max_length=500)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'chat_threads',
                'ordering': ['-last_activity_at'],
                'indexes': [models.Index(fields=['status', '-last_activity_at'], name='thread_status_recent_idx')],
            },
        ),
        migrations.CreateModel(
            name='ThreadFilter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active_filters', models.JSONField(blank=True, default=dict)),
                ('resolver_trace', models.JSONField(blank=True, default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('last_resolved_at', models.DateTimeField(blank=True, null=True)),
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filter_state', to='chats.chatthread')),
            ],
            options={
                'db_table': 'thread_filters',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], max_length=24)),
                ('content', models.TextField()),
                ('tool_name', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chatthread')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['position', 'created_at'],
                'indexes': [models.Index(fields=['thread', 'position'], name='thread_message_order_idx'), models.Index(fields=['role'], name='chat_message_role_idx')],
                'constraints': [models.UniqueConstraint(fields=('thread', 'position'), name='unique_message_position_per_thread')],
            },
        ),
    ]
