# Generated by Codex on 2026-04-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="threadfilter",
            name="latest_result_context",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="threadfilter",
            name="pending_booking",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
