# Generated by Django 6.0.4 on 2026-04-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_threadfilter_booking_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatthread',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('booked', 'Booked'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=24),
        ),
    ]
