# Generated by Django 6.0.4 on 2026-04-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_chatthread_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='mode',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('entertainment', 'Entertainment'), ('flights', 'Flights')], default='unknown', max_length=24),
        ),
    ]
