from django.urls import path

from apps.events.views import (
    event_types_view,
    movie_cast_members_view,
    movie_certifications_view,
    movie_content_origins_view,
    movie_directors_view,
    movie_formats_view,
    movie_franchises_view,
    movie_genres_view,
    movie_languages_view,
    movie_locations_view,
    movie_search_view,
    movie_titles_view,
    movie_venues_view,
    sport_away_teams_view,
    sport_competition_stages_view,
    sport_featured_athletes_view,
    sport_format_labels_view,
    sport_home_teams_view,
    sport_locations_view,
    sport_match_numbers_view,
    sport_organizers_view,
    sport_participant_names_view,
    sport_search_view,
    sport_season_labels_view,
    sport_teams_view,
    sport_tournaments_view,
    sport_types_view,
    sport_venues_view,
    temporal_normalization_view,
)

app_name = "events"

urlpatterns = [
    path("movies/search/", movie_search_view, name="movie-search"),
    path("sports/search/", sport_search_view, name="sport-search"),
    path("tools/event-types/", event_types_view, name="event-types"),
    path("tools/movies/locations/", movie_locations_view, name="movie-locations"),
    path("tools/movies/languages/", movie_languages_view, name="movie-languages"),
    path("tools/movies/genres/", movie_genres_view, name="movie-genres"),
    path("tools/movies/cast-members/", movie_cast_members_view, name="movie-cast-members"),
    path("tools/movies/directors/", movie_directors_view, name="movie-directors"),
    path("tools/movies/certifications/", movie_certifications_view, name="movie-certifications"),
    path("tools/movies/titles/", movie_titles_view, name="movie-titles"),
    path("tools/movies/venues/", movie_venues_view, name="movie-venues"),
    path("tools/movies/formats/", movie_formats_view, name="movie-formats"),
    path("tools/movies/franchises/", movie_franchises_view, name="movie-franchises"),
    path("tools/movies/content-origins/", movie_content_origins_view, name="movie-content-origins"),
    path("tools/sports/locations/", sport_locations_view, name="sport-locations"),
    path("tools/sports/types/", sport_types_view, name="sport-types"),
    path("tools/sports/tournaments/", sport_tournaments_view, name="sport-tournaments"),
    path("tools/sports/season-labels/", sport_season_labels_view, name="sport-season-labels"),
    path("tools/sports/competition-stages/", sport_competition_stages_view, name="sport-competition-stages"),
    path("tools/sports/format-labels/", sport_format_labels_view, name="sport-format-labels"),
    path("tools/sports/home-teams/", sport_home_teams_view, name="sport-home-teams"),
    path("tools/sports/away-teams/", sport_away_teams_view, name="sport-away-teams"),
    path("tools/sports/teams/", sport_teams_view, name="sport-teams"),
    path("tools/sports/participant-names/", sport_participant_names_view, name="sport-participant-names"),
    path("tools/sports/venues/", sport_venues_view, name="sport-venues"),
    path("tools/sports/featured-athletes/", sport_featured_athletes_view, name="sport-featured-athletes"),
    path("tools/sports/organizers/", sport_organizers_view, name="sport-organizers"),
    path("tools/sports/match-numbers/", sport_match_numbers_view, name="sport-match-numbers"),
    path("tools/temporal/normalize/", temporal_normalization_view, name="temporal-normalize"),
]
